server.port: 7002
server.error.include-message: always

spring.data.mongodb:
  authentication-database: admin
  username: admin
  password: contra123
  host: 192.168.3.220
  port: 27017
  database: recommendation-db


spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings.input:
    destination: recommendations
    group: recommendationsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
---
spring.profiles: docker

server.port: 8080

spring.data.mongodb.host: 192.168.3.220

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka